### ISSUE TITLE
2.2.1 release possible ?

### ISSUE THREAD

**Issue by NoCoker** [aparo/opensearch-analysis-ik#13]
As we upgrade to 2.2.1 in production already we would like to implement this plugin too:
https://github.com/opensearch-project/opensearch-build/blob/main/release-notes/opensearch-release-notes-2.2.1.md

Thanks

**Comment by aparo** [comment]
Done https://github.com/aparo/opensearch-analysis-ik/releases/tag/untagged-1d2128018d4c0d0ff9e5 ;-)
